### ISSUE TITLE
Has an errror querying channels while connecting to fabric environment

### ISSUE THREAD

**Issue by dannielboy58** [IBM/evote#16]
I have encountered an error whileee trying to start the fabric environment on Visual Studio Code
Here is the log out put 
**[ERROR] Error connecting to environment Local Fabric: Error: Error querying channels: Failed to connect before the deadline URL:grpc://localhost:17051**

here is the output of docker ps

bb7c0e54a06d        hyperledger/fabric-ca:1.4.4   "sh -c 'fabric-ca-..."   5 minutes ago       Up 5 minutes        7054/tcp, 0.0.0.0:17050->17050/tcp   fabricvscodelocalfabric_ca.org1.example.com

**Comment by horeaporutiu** [comment]
@dannielboy58 

Did you export the connection profile as shown in this step? https://github.com/IBM/evote/blob/master/docs/run-local.md#step-5-export-connection-details

Your connection profile should look like this:

```
{
    "certificateAuthorities": {
        "Org1CA": {
            "caName": "ca",
            "url": "http://localhost:17050"
        }
    },
    "client": {
        "connection": {
            "timeout": {
                "orderer": "300",
                "peer": {
                    "endorser": "300"
                }
            }
        },
        "organization": "Org1MSP"
    },
    "name": "Org1",
    "organizations": {
        "Org1MSP": {
            "certificateAuthorities": [
                "Org1CA"
            ],
            "mspid": "Org1MSP",
            "peers": [
                "Org1Peer1"
            ]
        }
    },
    "peers": {
        "Org1Peer1": {
            "url": "grpc://localhost:17051"
        }
    },
    "version": "1.0.0"
}
```

And then make sure the file name that you exported from that step is matches the file name from the `config.json` file. i.e. if you exported the file named `local_fabric_connection.json` then make sure that it matches up in your config.json file as follows:

```
{
  "connection_file": "local_fabric_connection.json",
  "appAdmin": "admin",
  "appAdminSecret": "adminpw",
  "orgMSPID": "Org1MSP",
  "caName": "ca.org1.example.com",
  "userName": "V1",
  "gatewayDiscovery": { "enabled": true, "asLocalhost": true }
}
```

**Comment by horeaporutiu** [comment]
That error is saying that the application could not find the node to submit the query to - and the way to find the node is through the connection profile. So either your Docker is not working properly, or something is incorrect with the connection profile.

**Comment by dannielboy58** [comment]
Works fine now
.... Config.json was incorrectly generated
