### ISSUE TITLE
Cannot find nodule : util.js

### ISSUE THREAD

**Issue by Krishna812** [IBM/evote#18]
While running this app on local, i encounter this error. Kindly help to resolve this.
![Capture](https://user-images.githubusercontent.com/37139394/75187763-bd00cf80-5718-11ea-99f4-40b55cef1b37.PNG)

**Comment by horeaporutiu** [comment]
@Krishna812 

try to clone the app again and run through the directions again - I've seen this error but it went away recently.

**Comment by C-PIG** [comment]
@Krishna812 
While running this app on local
What version of each environment do you use？
thanks

**Comment by Krishna812** [comment]
@horeaporutiu  Thanks i repeated the whole process again n this time i got new error : Database does not exist. 
![image](https://user-images.githubusercontent.com/37139394/75494803-07898280-598b-11ea-8001-c665e764dbe8.png)
How to resolve this

**Comment by Krishna812** [comment]
@C-PIG Im using ubuntu 18.0 and all the other softwares of the latest versions.

**Comment by horeaporutiu** [comment]
@Krishna812 @C-PIG 

That's strange - I've just tested this on my Macbook and all is working fine..may be a problem with Ubuntu..let my try and test this pattern on Ubutu. 

Using VSCode 1.42.1
IBM Blockchain Platform 1.0.20
```
aot-bc-space-cargo-api$ node -v
v8.9.0
aot-bc-space-cargo-api$ npm -v
6.11.3
aot-bc-space-cargo-api$ docker -v
Docker version 19.03.5, build 633a0ea
aot-bc-space-cargo-api$ docker-compose --version
docker-compose version 1.25.2, build 698e2846
```

**Comment by Krishna812** [comment]
@horeaporutiu 

Thanks for your help. I just resolved this by renaming my connection profile.

**Comment by horeaporutiu** [comment]
I see - the problem was `config.json` was not finding it right? 

I may make this more simple adding a `localConfig.json` with the `local_fabric_connection.json` already set. Thanks for bringing this up!
