### ISSUE TITLE
How to add new field 

### ISSUE THREAD

**Issue by Krishna812** [IBM/evote#21]
The voter can login just by voter id. How can I add the password and changing password functionality? In which file(s) do I have to make changes?

**Comment by horeaporutiu** [comment]
you would alter this file: https://github.com/IBM/evote/blob/master/web-app/client/src/components/Home.vue

You would likely have to make some backend calls though, and you would do that in this file: https://github.com/IBM/evote/blob/master/web-app/server/src/app.js

**Comment by horeaporutiu** [comment]
@Krishna812 Does this help?

**Comment by Krishna812** [comment]
yeah !!

**Comment by Krishna812** [comment]
thanks
