### ISSUE TITLE
no free cluster

### ISSUE THREAD

**Issue by jessezwd** [IBM/evote#3]
I have an account of IBM Cloud, but I can't get the free cluster of Kubernetes Service. Why?

**Comment by jessezwd** [comment]
It seems the free cluster is just for some cities only.

**Comment by horeaporutiu** [comment]
@jessezwd What is the error you are getting? You should be able to get a free cluster from IBM Kubernetes Service..have you tried switching the cluster to be in a different location?

**Comment by jessezwd** [comment]
@horeaporutiu Thanks for your comments. 
"Free clusters are not available with your current account type. Upgrade your account to create one." It seems the free clusters is not for me, right?
 I switched to be in different locations, but the result is the same.

**Comment by horeaporutiu** [comment]
@jessezwd 

You have to put in a credit card (and upgrade your account to Pay as You Go) to use the free Kubernetes cluster. As long as you just use the free Kubernetes cluster, your CC will not get charged. This is just to make sure you are not a robot and is standard across cloud providers. (Google and AWS ask for credit cards too for their free services).  

The IBM Blockchain service is free, as well, as long as it is linked to a free Kubernetes cluster. 

Hope this helps!

**Comment by jessezwd** [comment]
@horeaporutiu thanks a lot!
