### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by adityaverma998** [IBM/evote#34]
Hi
could you please tell me how can I run this on multiple nodes to get some research-based results like in the attachment below?
![result](https://user-images.githubusercontent.com/39986925/80898782-3de5d400-8d25-11ea-8f1b-9b69de52419f.png)

**Comment by horeaporutiu** [comment]
@adityaverma998 

Please refer to - https://github.com/IBM/raft-fabric-sample for running smart contract on multiple nodes ensuring fault tolerant consensus
