### ISSUE TITLE
Detailed Guide to understand your code

### ISSUE THREAD

**Issue by adityaverma998** [IBM/evote#35]
Good Morning Sir
Could you please provide me with some detailed guide to understand your code?
Like how things are working from the very basic, and which components are connected to which one, and how these are working interconnectively.
Please revert back asap.

**Comment by horeaporutiu** [comment]
please watch the two videos for guides on how to understand the code

![Screen Shot 2020-05-12 at 4 43 52 PM](https://user-images.githubusercontent.com/10428517/81756141-c542ee00-946f-11ea-8398-cdadd4a8c6fc.png)
