### ISSUE TITLE
Server not starting 

### ISSUE THREAD

**Issue by SasinduFdo** [IBM/evote#47]
PS C:\Users\Sasindu Fdo\Desktop\IBM Test\evote\web-app\server> npm run start
Debugger listening on ws://127.0.0.1:60526/c8d8f66a-e30a-4ffe-8fd8-a959c0f8fa7f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> server@1.0.0 start C:\Users\Sasindu Fdo\Desktop\IBM Test\evote\web-app\server
> ./node_modules/nodemon/bin/nodemon.js src/app.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `./node_modules/nodemon/bin/nodemon.js src/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sasindu Fdo\AppData\Roaming\npm-cache\_logs\2020-10-07T12_40_29_657Z-debug.log

**Comment by SasinduFdo** [comment]
It works

**Comment by khlilturki97** [comment]
@SasinduFdo how did u solved this ?

**Comment by prasad-kumkar** [comment]
use node 10.13.0
