### ISSUE TITLE
node v12.6.0 not ok?

### ISSUE THREAD

**Issue by jessezwd** [IBM/evote#6]
I tried "npm install" and got the following errors, I need change node v12.x to node v8.x, right?
make: *** [x509.target.mk:112：Release/obj.target/x509/src/addon.o] error 1
make: leaving “/home/.../evote/contract/node_modules/@ampretia/x509/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/.../.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.1.18-1-MANJARO
gyp ERR! command "/home/.../.nvm/versions/node/v12.6.0/bin/node" "/home/.../.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/.../evote/contract/node_modules/@ampretia/x509
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN voterContract@7.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ampretia/x509@0.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ampretia/x509@0.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by horeaporutiu** [comment]
@jessezwd Thanks for the question. I have only tested the pattern using Node version 8.9. I haven't tried using higher versions of Node. I recommend using Node 8.9.0. The reason is that that is what is required to use the IBM Blockchain VSCode extension as well, which is really useful for development.

**Comment by horeaporutiu** [comment]
@jessezwd Just duplicated this issue. Will update repo with node 8.9.0 as a prerequisite. Thank you for your help!
